import { Module } from '@nestjs/common';
import { PlatformModule } from './platform/platform.module.js';

/**
 * The app.
 *
 * `PlatformModule` is the framework; everything below it is product. A feature
 * generated by `pnpm boot:feature` adds one line here — deliberately, rather
 * than being auto-discovered from the filesystem, so that reading this file
 * tells you what the app actually is.
 */
@Module({
  imports: [PlatformModule],
})
export class AppModule {}
